educ:
    resource: "@EducBundle/Resources/config/routing.yml"
    prefix:   /

educate:
    resource: "@EducateBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
